### ISSUE TITLE
enhancement: show keys on records

### ISSUE THREAD

**Issue by githubmarker** [tslater2006/DMS-Viewer#12]
The `Columns` box shows a list of fields on the record, as well as their type, and size.

However, it would be useful to also display the keys on the record.
e.g. key, search key, alternate search key, etc.
At a minimum, even just "key" would be useful.

I'm have no idea this is data already being provided by the [DMSLib library](https://github.com/tslater2006/DMSLib/tree/c4e7f706dfb4d40d9d84970b5ccaa174701d3319) or if it would require new code.

![image](https://user-images.githubusercontent.com/1767017/55448630-56f9df80-557d-11e9-964d-48fca6b7900c.png)

suggested label: enhancement

**Comment by tslater2006** [comment]
Will add a Key column like this:
![image](https://user-images.githubusercontent.com/1731714/55521165-31380d80-5645-11e9-84bc-c45b6a0d8f76.png)

**Comment by tslater2006** [comment]
Of note, this wasn't initially possible because the DAT file only contains the column names in readable information. It wasn't until the record field metadata structures were deciphered that this became possible. 

Specifically by doing this 
```
var isKey = value.Metadata.FieldMetadata.Where(m => m.FieldName == col.Name).First().UseEditMask.HasFlag(UseEditFlags.KEY);
```
