### ISSUE TITLE
enhancement: generated sql should include schema prefix

### ISSUE THREAD

**Issue by githubmarker** [tslater2006/DMS-Viewer#13]
Looking at the SQL generated from a .DAT file, there is no schema prefix.

Since PeopleSoft uses the SYSADM schema, and there is no way to force a DMS script to import to an alternate schema (my assumption), then that should be the default schema.

This would allow search-and-replace script editing for anyone who wants to insert data into a user's private schema for testing/comparison/preservation of data as compared to the ACTUAL tables in the SYSADM schema.

suggested label: enhancement

**Comment by tslater2006** [comment]
To my knowledge the schema isn't stored in the DAT files, so this isn't something I can pull out and leverage during SQL generation. Perhaps an in-between would be to add an additional option on the SQL generation options for you to specify a schema, and if you do to prefix all of the tables with it.

This still wont let you import a DAT file to a different schema... though I guess if the tables already existed in your private schema then having SQL inserts would be useful.

**Comment by tslater2006** [comment]
Closing as you can now specify a schema value for generati g SQL, it should be prepended to the table names

**Comment by umaritimus** [comment]
also, please don't forget about the less fortunate sql server folk - in mssql universe, it's not `SYSADM`, but `dbo`, by default.  Either way, it's probably not the best idea to hardcode the schema
