### ISSUE TITLE
enhancement: modify spreadsheet copy/paste to contain LONG type data in a single cell

### ISSUE THREAD

**Issue by githubmarker** [tslater2006/DMS-Viewer#14]
steps to reproduce:
1) open .dat file
2) select record which has at least one row of data and at least column with type LONG 
3) click "view data" button
4) select all
5) copy
6) open microsoft excel
7) paste

expected results:
- displayed contents of excel spreadsheet match displayed contents of Data Mover spreadsheet cell-for-cell

actual results:
- excel paste of spreadsheet contents splits LONG data into multiple rows of data and causes non-multi-row data to merge multiple cells to compensate

This makes further copy/pasting/spreadsheet comparison difficult since the for the LONG field is no longer contained in a single cell.

suggested label: enhancement

**Comment by githubmarker** [comment]
suggested label: enhancement

**Comment by tslater2006** [comment]
Unfortunately this behavior is built-in/delivered with the control by Microsoft. The data gets copied to the clipboard as tab separated values, and when a long data field contains line breaks, it breaks out onto separate lines. This isn't something within my control to fix.
