### ISSUE TITLE
enhancement: spreadsheet copy/paste row/column headers don't copy as anticipated

### ISSUE THREAD

**Issue by githubmarker** [tslater2006/DMS-Viewer#15]
a) copy/pasting from the spreadsheet view DOES NOT include headers at the top of the columns

b) copy/pasting from the spreadsheet view DOES include an empty column to the left of the data

suggested label: enhancement

**Comment by tslater2006** [comment]
Similar to #14, these behaviors are from the control itself and not code DMS Viewer has. I don't really have control over this behavior. Though note that if you don't select the rows by the row header you do not get the empty column on the left.
