### ISSUE TITLE
enhancement: should be possible to save spreadsheet to file

### ISSUE THREAD

**Issue by githubmarker** [tslater2006/DMS-Viewer#16]
spreadsheet should be saveable to file possibly csv/excel/other?

this could be accomplished via right-click context menu, or some other method.

suggested label: enhancement

**Comment by tslater2006** [comment]
This is an interesting idea, and perhaps makes up for the other issues regarding the data grid. I'll look to add a "Save to excel" button or something, assuming I can find an easy way to write Excel files.

**Comment by tslater2006** [comment]
This functionality was introduced by commit 0e86046. Note there is now an additional dependency required for the excel sheet writing functionality.

Select 1 or more records in the record list (ctrl to pick and choose, shift to select a range), right click and click Export to Excel. Each record will be its own sheet.
