### ISSUE TITLE
enhancement: copy record list button should produce cleaner output

### ISSUE THREAD

**Issue by githubmarker** [tslater2006/DMS-Viewer#17]
"copy record list" button copies text to the clipboard as follows:

`ListViewItem: {PSCLOCK}`
or
```
ListViewItem: {PSCLOCK}
ListViewItem: {INSTALLATION}
```
but it should just copy the actual record name (the part between the curly braces {}).
e.g.
`PSCLOCK`
or
```
PSCLOCK
INSTALLATION
```

suggested label: enhancement

**Comment by githubmarker** [comment]
suggested label: enhancement

**Comment by tslater2006** [comment]
Early on DMS Viewer used a combo box for that listing, instead of a listview. Switching to list view caused the dirty output. All fixed, thanks for reporting!
