### ISSUE TITLE
enhancement: display name of dat file in header of main window

### ISSUE THREAD

**Issue by githubmarker** [tslater2006/DMS-Viewer#18]
It would be useful to Include the name of the open dat file (and posssibly its path) in the header of the DMS Viewer application.

FYI, some modification of the text in the header is already taking place when clicking the "compare to db" button, which appears to show the db name in the header.

This would be helpful to keep track of which .dat file is being opened/viewed/compared when the user has multiple .dat files in need of examination.

suggested label: enhancement

**Comment by tslater2006** [comment]
I've never liked the DB name in the header, going to move this to a status strip on the bottom (and include file path).

![image](https://user-images.githubusercontent.com/1731714/55522115-372fed80-5649-11e9-829b-aeb09d649cbc.png)
