### ISSUE TITLE
crash when clicking whitespace within records box then view data button

### ISSUE THREAD

**Issue by githubmarker** [tslater2006/DMS-Viewer#7]
Seems like the cursor defaults to the first record in the list by default (but doesn't highlight it to indicate that).

If you click the white part of the inside of the "records" box but don't succeed in highlighting an actual record row, then clicking "view data" will cause an error.

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ```
> ************** Exception Text **************
> System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 'index'.
> Parameter name: index
>    at System.Windows.Forms.ListView.SelectedListViewItemCollection.get_Item(Int32 index)
>    at DMS_Viewer.Form1.dataViewer_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.Control.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>    at System.Windows.Forms.Button.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> ```
![01](https://user-images.githubusercontent.com/1767017/55374055-053d5080-54bc-11e9-9e01-d2575e61457a.png)

some possible behaviors that can mitigate this:

-  highlight the default record

- clicking the white space should highlight the default record

- clicking the whitespace to the right of a record should highlight the record even when it's not really close by

- clicking whitespace can deselect all records but view data button should take no action

**Comment by tslater2006** [comment]
Fixed by commit b8a82ca3

**Comment by githubmarker** [comment]
Looking at the code from commit b8a82ca, the chosen solution appears to have been:

- if record has been selected, allow clicking of the buttons on the right

    - else disable the buttons so they can't be clicked

or something like that
