### ISSUE TITLE
enhancement: comparedb requires more clicks than necessary

### ISSUE THREAD

**Issue by githubmarker** [tslater2006/DMS-Viewer#9]
1)
When using the Compare DB feature, it prompts on every record in the list.

It asks again and again whether the same db connection should be reused.

I think the default assumption should be yes.
Perhaps it could ask once for confirmation when you change .dat files?

I'm trying to figure out why the current work flow is as it is.
I'm guessing perhaps it's to accommodate the use case where one is trying to compare one dat file to multiple databases?

That seems worth of handling, but also a seems like it wouldn't be the most common use case.

I think the most common use case is to compare all the records in a .dat file using a single database connection.
That, IMO, more common use case would be better served by defaulting to re-use the connection for the current .dat file.

2)
Going back to the typical presumed used case, comparing all records in a .dat file to a database...

It might be useful to automatically compare all records to DB upon clicking the compare to db button. That could potentially reduce the number of prompts and still prompt people to switch databases each time they click the button.

If we are trying to protect users from comparing a large amount of data by accident, perhaps a different button "compare all records to db" could exist.

suggested label: enhancement

**Comment by githubmarker** [comment]
suggested label:
enhancement

**Comment by tslater2006** [comment]
I am going to move the database connection to the tool bar on the top connect/disconnect. if connected the DB compare button will be enabled (assuming a DMS file is open and something is selected).

Regarding the ability to compare the entire DAT, I'm going to adjust the compare button to allow "compare selected" and you will be able to multi-select the tables and then run the compare on all of them.

**Comment by tslater2006** [comment]
![image](https://user-images.githubusercontent.com/1731714/55520669-fcc35200-5642-11e9-9ca1-c5685297c351.png)
